### PR TITLE
Add `order_desc` for ordering Imports, Remotes, Suggests fields alphabetically

### PR DESCRIPTION
**Pull request by yogat3ch**
Function & Documentation for `order_desc` which alphabetizes the fields in the description where alphabetization makes sense.

### CODE REVIEW

**Comment by yogat3ch** [comment]
@yonicd Thoughts on adding this functionality?

**Comment by yonicd** [comment]
it seems to be doing things similar to fns in https://github.com/yonicd/sinew/blob/master/R/makeImport.R, can you add sorting arg to those fns instead?

**Comment by yogat3ch** [comment]
@yonicd Doing so would mean creating a conditional around the majority of the functionality in makeImport and the `script` required argument doesn't pertain to `order_desc`. The use case for `order_desc` is for ordering the remotes, suggest, imports in a package where the maintainers have just been adding entries in these fields by hand, or using `usethis::use_package` which appends new packages to the end (unordered). 

I feel like it makes more sense as a standalone function as makeImports does a great deal more. Thoughts?

**Comment by yonicd** [comment]
closing stale PR

**Pull request closed without merging**
