### PR TITLE
Add copy to clipboard (#74) and markdown formatting (#78) features to `makeOxygen()`

### PR DESCRIPTION
**Pull request by elipousson**
Also:
- Replace use of `writeLines()` when printing output with `cli_code()`
- Minor fixes to DESCRIPTION by removing miniUI + shiny from Imports + adding "Encoding: UTF-8"

### CODE REVIEW

**Comment by elipousson** [comment]
If this is a welcome pull request, it may be helpful to add an option to set the `use_md` parameter globally. Happy to add that in but wanted to check first.

**Comment by yonicd** [comment]
thanks for the PR. I will review it shortly

**Review by yonicd — APPROVED** [review]

**Comment by yonicd** [comment]
Gha shows that {crayon} is missing from desc file

**Comment by elipousson** [comment]
I’ll take a look and also fix the test coverage issues! The scope of this PR expanded a good bit beyond my initial draft back in August when I got back to it last night so, if you want some but not all of the code, just let me know and I can pull those changes back out again.

**Comment by elipousson** [comment]
I think I got the code coverage issues fixed.

The main additions beyond the original additional of auto-copying with `{clipr}` and markdown formatting with `{roxygen2md}` include:

- Refactoring `makeOxygen()` with new helper functions, new parameters for title/description, and the option to pull label parameters for data frame columns (enabled using the use_labels parameter), and adding support for vector data objects
- Refactoring `makeOxyFile()` to improve support for directory inputs and add `dir.out` parameter and to expose the new parameters added to `makeOxygen()`
- Convert error/informational messages to work with the cli package
- Update `makeDictionary()` to handle file as well as directory input paths
- Update tests and documentation to match the modified functions and add snake case-style aliases for several functions

I use sinew all the time and I'd love to get these changes into the package if possible. Let me know if any additional changes are needed!

**Review by yonicd — APPROVED** [review]

**Comment by yonicd** [comment]
@elipousson thanks again for all the contributions and hard work of thinking how to refactor the package.

**Comment by elipousson** [comment]
@yonicd My pleasure! I have a few additional tweaks in mind but didn't want to crowd an already crowded PR after you had already signed off. Time permitting, I may open a new GitHub issue with those ideas in the next few weeks.

**Pull request merged**
