### PR TITLE
interactiveAddIn

### PR DESCRIPTION
**Pull request by grishin1**
- The current `createOxygen` add-in can only be used with a limited number of default arguments to `makeOxygen` which limits its usefulness. In my opinion,  this warrants implementation of an interactive add-in.
- I propose an interactive add-in which:
  - opens up in the viewer panel, user can select object’s name in the source editor (like current add-in).
  - allows selection of __any__ parameters to `makeOxygen` and underlying `makeImport`.
  - enables multiple application of `makeOxygen` in a file without need to navigate to the menu and launch  add-in multiple times – just insert as many as you like and press “Quit”.
  - if objects are not found user is asked to source the file which happens in a temporary environment without contaminating .GlobalEnv.
  - contains all allowed `makeOxygen` entries for “add_fields” argument. No need to remember or keep a list of them. 
- Typical use – inserting comments for single functions in the process of package development “as you go”.
- Adds dependency on `shiny` and `miniUI` packages
- I've decided to export add-in function to document usage (details contain brief description of workflow) and to make possible launching add-in programmatically, not via menu.
- You can quickly try out all functions I propose by github installing 'demo' branch:
`devtools::install_github("grishin1/sinew", ref = "demo")`

### CODE REVIEW

**Comment by yonicd** [comment]
thanks for the suggested contribution. The direction is interesting. I have been in contact with Rstudio to have them open up the right click contextmenu's for user defined fields, that way options can be chosen wo the need for a miniUI.

regarding your script it has a few bugs in it that saw. 

if there is no global obj it tries to source it but breaks with:
```r
Listening on http://127.0.0.1:3128
Warning: Error in sys.source: '' is not an existing file
Stack trace (innermost first):
    68: sys.source
    67: observeEventHandler
     3: shiny::runApp
     2: runGadget
     1: sinew:::interOxyAddIn
```

when clicking on use_dictionary it breaks with:

```r
Listening on http://127.0.0.1:3128
Warning: Error in observeEventHandler: could not find function "choose.files"
Stack trace (innermost first):
    67: observeEventHandler
     3: shiny::runApp
     2: runGadget
     1: sinew:::interOxyAddIn
ERROR: [on_request_read] connection reset by peer
```

on this I would make it a `conditionalUI` on the existence of the subdir `man-roxygen`, but in general I would keep it to one MiniUI page, most of the options in the more args page the user doesnt need to adjust, the cutoff and the dictionary can be placed in the first page.

**Comment by grishin1** [comment]
1. You need to have an open file before launching add-in, currently. Should be fixable.
2. Strange, last time I tested 'use dictionary' worked fine for me. I'll have a look.
3. I agree, one page might be better as the second one contains only one ('cut') often used argument.

**Comment by yonicd** [comment]
what do you mean an 'open file'?

**Comment by grishin1** [comment]
I meant a file opened in the source editor but upon re-reading your comment I can see it doesn't make sense. I missed that bit about sourcing. So it breaks on sourcing. So far I haven't seen that, I'll look into this.

Although "" in your reprex may mean exactly that. Did you have a file in the editor?

**Comment by yonicd** [comment]
yes. i highlighted the function name in the editor

**Comment by grishin1** [comment]
- Just wondering about right click context menu approach in Rstudio. Normally they disappear after a single click. How would it be possible to select 5 entries for makeOxygen's `add_fields`?
- Bugs: I tried on a different machine today and it worked for me. Regarding your reprex:
1. Empty quotes suggest that `sys.source` did not get a file name. I can't really see how this could happen if an R file was opened in the source editor and a selection made before launching addin. Could you please try a couple times more with different files?
2. `choose.files` was not found. I thought this function is  in `base` but it's in fact in `utils`. I would think that `utils` is always attached by default and R has no problems finding it. Could you check if your R sessions has `utils` attached? The cure may be as simple as `utils::choose.files`
- A small problem with the conditional panel for the dictionary is assumption that it should be in `man-roxygen` directory. Or is it a requirement? Can it be anywhere?

Anyway, there are a few things to re-write. I'll get back to you once it's done.

**Comment by yonicd** [comment]
1. [this](https://anseki.github.io/jquery-contextmenu-common/) can be used for context menu's

  2. i don't see choose.files in the utils namespace

```r
ls(name = 'package:utils',pattern = '^choose')
[1] "chooseBioCmirror" "chooseCRANmirror"
```

  3. that directory is the roxygen default for template files which is what the dictionary basically is.

**Comment by grishin1** [comment]
1. Nice, would be good to have in Rstudio.
2. This one is interesting. This is what I get:
``` r
ls(name = "package:utils", pattern = "^choose")
#> [1] "choose.dir"       "choose.files"     "chooseBioCmirror"
#> [4] "chooseCRANmirror"
```
My utils version is 3.4, consistent with [this](https://www.rdocumentation.org/packages/utils/versions/3.4.0/topics/choose.files) but , strange enough, not with [this](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/00Index.html#C). `choose.dir` and `choose.files` are not there anymore.
Are you using dev. version of R/utils?
3. OK

**Comment by grishin1** [comment]
It slipped from my attention that `choose.files()` is a Windows-specific dialogue:
> This is only available on Windows.

from `choose.files` documentation
So set of util's functions will be OS-dependent.

**Comment by yonicd** [comment]
Yes. I've run into that with system() vs shell()

**Comment by grishin1** [comment]
I have now pushed fresh changes:
- Simplified UI and the number of passed parameters , as discussed
- Conditional panel for choosing dictionary
- `base::file.choose()` instead of `utils::choose.files()`
- Updated logic especially for starting without a file in the editor.
- More details on how to use in the docs

**Comment by yonicd** [comment]
that looks much better. 


when i close the gadget i get this error

```r
Error in detach("interOxyEnvir") : invalid 'name' argument
```

i rewrote the addin to have a preview pane and organize the checkbox group better:

```r
#' @title Interactive add-in
#' @description Launches an interactive addin for insertion of roxygen2 comments in files.
#' Allows selection of extra parameters for \code{makeOxygen}
#' @return Nothing. Inserts roxygen2 comments in a file opened in the source editor.
#' @author Anton Grishin
#' @details Open an .R file in Rstudio's source editor.
#' Launch the add-in via Addins -> interactiveOxygen or interOxyAddIn() in the console.
#' Add-in opens in the viewer panel.
#' Select function's/dataset's name in the source editor.
#' If objects cannot be found, the addin prompts to source the file.
#' Choose parameters for \code{makeOxygen}. Click Insert.
#' Select next object's name. Rinse.Repeat. Click Quit when done with the file.
#' @examples
#' interOxyAddIn() # launches interactive add-in, alternatively,
#' Rstudio menu Addins -> 'interactiveOxygen' 
#' @export 
#' @rdname interOxyAddIn
#' @seealso \code{View(sinew:::oxygenAddin)}
#' @import rstudioapi
#' @import shiny
#' @import miniUI
interOxyAddIn <- function() {
  
  #on.exit(detach("interOxyEnvir"))
  
  tweaks <- 
    list(tags$head(tags$style(HTML("
                                   .multicol { 
                                   height: 300px;
                                   -webkit-column-count: 3; /* Chrome, Safari, Opera */ 
                                   -moz-column-count: 3;    /* Firefox */ 
                                   column-count: 3; 
                                   -moz-column-fill: auto;
                                   -column-fill: auto;
                                   } 
                                   ")) 
    ))
  
  header_add = c(author = "AUTHOR [AUTHOR_2]", backref = "src/filename.cpp", 
                 concept = "CONCEPT_TERM_1 [CONCEPT_TERM_2]", describeIn = "FUNCTION_NAME DESCRIPTION", 
                 details = "DETAILS", example = "path_to_file/relative/to/packge/root", 
                 examples = "\n#' \\dontrun{\n#' if(interactive()){\n#'  #EXAMPLE1\n#'  }\n#' }", 
                 export = "", family = "FAMILY_TITLE", field = "FIELD_IN_S4_RefClass DESCRIPTION", 
                 format = "DATA_STRUCTURE", importClassesFrom = "PKG CLASS_a [CLASS_b]", 
                 importMethodsFrom = "PKG METHOD_a [METHOD_b]", include = "FILENAME.R [FILENAME_b.R]", 
                 inherit = "[PKG::]SOURCE_FUNCTION [FIELD_a FIELD_b]", 
                 inheritDotParams = "[PKG::]SOURCE_FUNCTION", inheritSection = "[PKG::]SOURCE_FUNCTION [SECTION_a SECTION_b]", 
                 keywords = "KEYWORD_TERM", name = "NAME", rdname = "FUNCTION_NAME", 
                 references = "BIB_CITATION", section = "SECTION_NAME", 
                 source = "\\url{http://somewhere.important.com/}", slot = "SLOTNAME DESCRIPTION", 
                 template = "FILENAME", templateVar = "NAME VALUE", useDynLib = "PKG [ROUTINE_a ROUTINE_b]")
  
  controls<-list(h3("Select Fields to add to Oxygen Output"),
                 tags$div(align = 'left', 
                          class = 'multicol',
                          checkboxGroupInput(inputId = "fields",
                                             label = '',
                                             choices = names(header_add),
                                             selected = c("examples", "details", "seealso", "export", "rdname")))
  )
  
  ui <- miniUI::miniPage(
    tweaks,
    miniUI::gadgetTitleBar(textOutput("title", inline = TRUE),
                           left = miniUI::miniTitleBarButton( "qt", "Quit"),
                           right = miniUI::miniTitleBarButton(inputId = "insrt","Insert",
                                                              primary = TRUE)),
    miniUI::miniContentPanel(
      sidebarLayout(sidebarPanel = sidebarPanel(
        controls,
        hr(style = "border-top: 3px solid #cccccc;"),
        sliderInput(inputId = "cut", label = "cut", value = 0,
                    min = 0, max = 20, step = 1, ticks = FALSE),
        br(),
        uiOutput("cutslider"),
        br(),width = 5 
      ),
      mainPanel = mainPanel(
        verbatimTextOutput('preview'),width=7
      ))
    )
  )
  
  server <- function(input, output, session) {
    
    output$title <- renderText({paste0("Select parameters in makeOxygen(\"",robj()$selection[[1]]$text,  "\"...)")})
    observeEvent(input$no, stopApp())
    rfile <- reactiveVal()
    output$dictfile <- renderText({rfile()})
    
    output$cutslider <- renderUI({if (dir.exists("./man-roxygen")) {
      div(div(actionLink("butt", "use_dictionary",
                         icon = icon("folder-open", "glyphicons")),
              textOutput("dictfile")), hr())
    } else {p()}
    })
    
    robj <- reactivePoll(1000, session,
                         checkFunc = rstudioapi::getActiveDocumentContext,
                         valueFunc = rstudioapi::getActiveDocumentContext
    )
    
    observeEvent(robj(), {
      path <- robj()$path
      obj <- robj()$selection[[1]]$text
      
      if (!nzchar(path)) {
        showModal(modalDialog(
          title = HTML(paste0("Open an .R file in the source editor and ",
                              "<strong><u>select</u></strong> object's name!")),
          easyClose = TRUE)
        )
      }
      
      if (nzchar(obj) && is.null(get0(obj)) && !"interOxyEnvir" %in% search()) {
        showModal(modalDialog(title = paste(dQuote(obj), "not found!",
                                            "Do you want to source", 
                                            basename(rstudioapi::getSourceEditorContext()$path),
                                            " file or quit add-in?"),
                              footer = tagList(actionButton("no", "Quit Add-in"),
                                               actionButton("ok","Source"))
        ))}
      
    })
    
    observeEvent(input$qt, {
      if ("interOxyEnvir" %in% search()) detach("interOxyEnvir"); stopApp()})
    
    observeEvent(input$ok, {
      nenv <- attach(NULL, name = "interOxyEnvir")
      sys.source(rstudioapi::getSourceEditorContext()$path, nenv,
                 keep.source = TRUE)
      removeModal()
    })
    
    observeEvent(input$butt, {
      hh <- NULL
      try(hh <- file.choose(), silent = TRUE)
      rfile(hh)})
    
    observeEvent(input$insrt, {
      obj <- robj()$selection[[1]]$text
      if (!nzchar(obj) ||
          (is.null(get0(obj)) && "interOxyEnvir" %in% search())) {
        showModal(modalDialog(
          tags$h4(style = "color: red;","Make valid object selection!"),
          size = "s", easyClose = TRUE)
        )
      } else {
        ctxt <- rstudioapi::getSourceEditorContext()
        params <- list(obj = obj,
                       add_fields = input$fields,
                       add_default = TRUE,
                       print = FALSE,
                       use_dictionary = rfile(),
                       cut = input$cut
        )
        ins_txt <- do.call(sinew::makeOxygen, params)
        rstudioapi::insertText(ctxt$selection[[c(1,1)]],paste0(ins_txt, "\n",obj),id = ctxt$id)
      }})
    
    observeEvent(c(input$fields,robj()),{
      params <- list(obj = robj()$selection[[1]]$text,
                     add_fields = input$fields,
                     add_default = TRUE,
                     print = FALSE,
                     use_dictionary = rfile(),
                     cut = input$cut
      )

      output$preview<-renderText({
        if(nchar(params$obj)>0) do.call(sinew::makeOxygen, params)
      })
      
    })
    
    
  }
  runGadget(ui, server, viewer = paneViewer(minHeight = 450))
  }

```

**Comment by yonicd** [comment]
i added a version of the interactive addin to the master. btw what is your twitter handle?

**Comment by grishin1** [comment]
I've had a quick play with the add-in. The preview panel is a good idea -- looks nice. The grouped checkboxes look a bit skewed (left column lower than middle and right, top right checkbox is semi-clipped) for me but this is a minor thing.
Used `moga()` a couple of times, noticed that it produces "X[[i]]" in rdname field unlike the add-in which properly inserts function's name.
Thanks for #5 , #6 , #7. BTW I'm not on Twitter, I'll let you know if I get '@something' :)

**Comment by yonicd** [comment]
the skew is due to the label of the checkbox is part of the original div and is too much trouble to remove, so setting it to '' still keeps a place holder for the label. i'll expand the width to unclip the right column. 

didnt see that in moga yet. what are you running to get that?

the one thing that i cant seem to figure out is that in the addin if you are in update mode and click on a new checkbox the preview disappears and then reappears the if you click on another checkbox.

good choice on twitter. i added you as a ctb to pkg description, wanted to add some contact info to the field.

**Pull request merged**
