### PR TITLE
makeOxyFile, new function

### PR DESCRIPTION
**Pull request by grishin1**
- New function `makeOxyFile` added.
- Automatically inserts roxygen2 comments in file(s) by applying `makeOxygen` to all suitable objects. No need to copy/paste `makeOxygen` output from console.
- Allows to pass any parameters to `makeOxygen` / `makeImport`
- Input is one or more files, or all .R files in a directory
- Loading functions definitions in global environment is not needed. If file’s objects cannot be found (e.g. not in .GlobalEnv or on the search path) `makeOxyFile` asks to source the file. Evaluates objects in a temporary environment.
- Typical use  would be 'bulk mode' – wrapping a set of scripts/functions into a package.
- You can quickly try out all functions I propose by github installing from 'demo' branch: `devtools::github_install("grishin1/sinew", ref = "demo")`

### CODE REVIEW

**Comment by yonicd** [comment]
thanks for the suggested contribution, it looks good. a couple of questions. 

  - how would it work with r files that have multiple functions in them? 
  - is it possible to expand it to point to the data subdir and write to disk the data-man.R files in the R subdir using makeOxygen?

**Comment by grishin1** [comment]
- It inserts output of `makeOxygen` above definition of every function in a file. Multiple functions in a file is pretty common so this functionality is essential.
- If I understand your request correctly, yes it is already possible. Just point it to a file or a directory with .R data files and data objects will  get comments made by `makeOxygen`. If you have some specific scenario please provide more details.

**Comment by yonicd** [comment]
```r
> library(sinew)
> dir()
 [1] "cran-comments.md" "DESCRIPTION"      "inst"            
 [4] "man"              "man-roxygen"      "Miscellaneous"   
 [7] "NAMESPACE"        "R"                "README.md"       
[10] "sinew.Rproj"
> list.files('R')
[1] "importAddin.R"    "ls_param.R"       "makeDictionary.R"
[4] "makeImport.R"     "makeOxygen.R"     "makeSeeAlso.R"   
[7] "oxygenAddin.R"    "rmOxygen.R"       "tabular.R" 
> makeOxyFile('R/oxygenAddin.R')
makeOxygen() can't fine some objects in the global environment
would you like to parse oxygenAddin.R file?
y/n y
Error in get(x) : object 'context' not found
> ?makeOxyFile
> makeOxyFile('./R/oxygenAddin.R')
makeOxygen() can't fine some objects in the global environment
would you like to parse oxygenAddin.R file?
y/n y
Error in get(x) : object 'context' not found
```

**Comment by grishin1** [comment]
I'm able to reproduce this bug by giving makeOxyFile the same file you used. I'll have a look.
Does it work OK on other files for you?

**Comment by grishin1** [comment]
- The bug (thanks @yonicd) involving locally defined variables has been fixed. The function will process top level objects only. A known issue is a case when local variables/functions have the same name as some other top level objects in the file. I can address that later on.
- `utils::choose.files()` has been replaced with OS-independent `base::file.choose()` (see my comments in #6).
-  If the file already contains roxygen2 comments, these lines get deleted to prevent duplication. A description line added in details section of documentation.
- Temporary sourcing environment has received a fancier name (a bit more unique, just in case).

**Comment by yonicd** [comment]
still something wrong. im trying it out on the [ggedit](https://github.com/metrumresearchgroup/ggedit) pkg function [aesColour.R](https://github.com/metrumresearchgroup/ggedit/blob/master/R/aesColour.R)

```r
sinew::makeOxyFile('../ggedit/R/aesColour.R',overwrite = FALSE)
Error: No functions or data frames found in
/Users/jonathans/projects/ggedit/R/aesColour.R
In addition: Warning message:
In readLines(FILE) :
  incomplete final line found on '../ggedit/R/aesColour.R'
```

**Comment by grishin1** [comment]
Thank you for the find.
It's quite straightforward: function `aesColour()` uses `"="` for assignment
`aesColour=function(type) ...`
It's against good R coding style and my (wrong) assumption that `"<-"` is expected before `"function"`.
I'll make necessary changes in a little while.

**Comment by yonicd** [comment]
you should never assume the good in (the coding of) end users :)

**Comment by grishin1** [comment]
> you should never assume the good in (the coding of) end users :)

Agreed. It's amazing what people come up with for tests :)
Anyway, the problem with `"="` assignment is fixed. It now works on aesColour.R.

**Comment by yonicd** [comment]
Looks good. I added this [fn](https://github.com/metrumresearchgroup/sinew/blob/master/R/moga.R)

It is a bit more nuisanced to workflow

**Pull request merged**
