### PR TITLE
appropriate roxygen tags for data, and compact data description table

### PR DESCRIPTION
**Pull request by andrewdolman**
The current output of makeOxygen, when applied to a dataframe, adds roxygen tags for @export, @rdname and @examples. These are either not relevant of not advised for documenting data. (at least according to Hadley http://r-pkgs.had.co.nz/data.html#documenting-data). I suggest changing "add_fields" to  add_fields <- c("details", "source") when documenting data. I may not have suggested the best way to do this as I did not use sinew_opts, and basically overwrite add_fields if the object type is data.frame or tibble.

Also use a tabular format for the data description rather than \describe{} as it is much more compact.

### CODE REVIEW

**Comment by yonicd** [comment]
thank you for the PR. 

i would suggest to try first these steps, before changing the current method.

```r
my_fields <- sinew::sinew_opts$get('add_fields')

#edit my_fields

sinew::makeOxygen(stats::lm,add_fields=my_fields)

```

this way you can define the fields you need once and then use them where ever needed, while keeping defaults in place. 

The tabular vs describe is an interesting point. When creating the template we looked at same link you referenced and went by it. If we do use tabular instead i would rather use the internal tabular builder (`sinew::tabular()`) instead of building it by hand.

**Comment by andrewdolman** [comment]
> On 4. Dec 2017, at 15:49, yonicd <notifications@github.com> wrote:
> 
> thank you for the PR.
> 
> i would suggest to try first these steps, before changing the current method.
> 
> my_fields <- sinew::sinew_opts$get('add_fields')
> 
> #edit my_fields
> 
> sinew::makeOxygen(stats::lm,add_fields=my_fields)

This would of course work for me. But doesn’t it make sense to have the correct default for different object types?



> this way you can define the fields you need once and then use them where ever needed, while keeping defaults in place.
> 
> The tabular vs describe is an interesting point. When creating the template we looked at same link you referenced and went by it. If we do use tabular instead i would rather use the internal tabular builder (sinew::tabular()) instead of building it by hand.
> 

Good point. Somehow I overlooked that Hadley suggests the \describe format.

sinew::tabular() will recreate the whole data frame though. Whereas what we want is just the headers. The suggested code creates this automatically from the passed data object. 


Anyway, just some suggestions. 


Andrew.

**Comment by yonicd** [comment]
i meant this as sinew::tabular

```r
writeLines(sinew::tabular(data.frame(var=sprintf('\\code{%s}',names(mtcars)),DESCRIPTION='COLUMN DESCRIPTION')))
#' \tabular{ll}{
    #' \strong{var} \tab \strong{DESCRIPTION}\cr
    #' \code{mpg}  \tab COLUMN DESCRIPTION\cr
    #' \code{cyl}  \tab COLUMN DESCRIPTION\cr
    #' \code{disp} \tab COLUMN DESCRIPTION\cr
    #' \code{hp}   \tab COLUMN DESCRIPTION\cr
    #' \code{drat} \tab COLUMN DESCRIPTION\cr
    #' \code{wt}   \tab COLUMN DESCRIPTION\cr
    #' \code{qsec} \tab COLUMN DESCRIPTION\cr
    #' \code{vs}   \tab COLUMN DESCRIPTION\cr
    #' \code{am}   \tab COLUMN DESCRIPTION\cr
    #' \code{gear} \tab COLUMN DESCRIPTION\cr
    #' \code{carb} \tab COLUMN DESCRIPTION
#'}
```

**Comment by yonicd** [comment]
https://github.com/metrumresearchgroup/sinew/commit/47d90013e915714c4323de0264c1686a215193ed

**Comment by yonicd** [comment]
this feature has been added to the package

**Pull request closed without merging**
